# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_dmvnorm_arma_mult <- function(x, mean, sigma) {
    .Call(`_DPMMmlogit_log_dmvnorm_arma_mult`, x, mean, sigma)
}

log_dmvnorm_arma_sing <- function(x, mean, sigma) {
    .Call(`_DPMMmlogit_log_dmvnorm_arma_sing`, x, mean, sigma)
}

invHess <- function(B, y_k, R_k, betaMat, J) {
    .Call(`_DPMMmlogit_invHess`, B, y_k, R_k, betaMat, J)
}

rmvnormrcpp <- function(n_, mu_, sigma_) {
    .Call(`_DPMMmlogit_rmvnormrcpp`, n_, mu_, sigma_)
}

rmvnormrcpp_chol <- function(n, mu, col_sigma) {
    .Call(`_DPMMmlogit_rmvnormrcpp_chol`, n, mu, col_sigma)
}

chol_rcpp <- function(matrix) {
    .Call(`_DPMMmlogit_chol_rcpp`, matrix)
}

riwish_rcpp <- function(nu, upsilon) {
    .Call(`_DPMMmlogit_riwish_rcpp`, nu, upsilon)
}

riwish_rcpp_chol <- function(nu, chol_inverse_upsilon) {
    .Call(`_DPMMmlogit_riwish_rcpp_chol`, nu, chol_inverse_upsilon)
}

logdiwish_rcpp <- function(nu, upsilon, Draw) {
    .Call(`_DPMMmlogit_logdiwish_rcpp`, nu, upsilon, Draw)
}

prob_mlogit <- function(beta, R_p) {
    .Call(`_DPMMmlogit_prob_mlogit`, beta, R_p)
}

